{% set version = "3.1-0" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-hyper2
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/hyper2_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/hyper2/hyper2_{{ version }}.tar.gz
  sha256: 20822d9ca0a900b3d783c3ca1d497bfea7dfe3ea095ea3a9214bc7a6603e7685

build:
  merge_build_host: true  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ stdlib("c") }}                # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ stdlib("m2w64_c") }}          # [win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-rcpp >=1.0_7
    - r-alabama
    - r-calibrator
    - r-cubature
    - r-disordr >=0.0_9
    - r-magrittr
    - r-mathjaxr
    - r-partitions
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - r-rcpp >=1.0_7
    - r-alabama
    - r-calibrator
    - r-cubature
    - r-disordr >=0.0_9
    - r-magrittr
    - r-mathjaxr
    - r-partitions

test:
  commands:
    - $R -e "library('hyper2')"           # [not win]
    - "\"%R%\" -e \"library('hyper2')\""  # [win]

about:
  home: https://github.com/RobinHankin/hyper2
  license: GPL-2.0-or-later
  summary: A suite of routines for the hyperdirichlet distribution; supersedes the 'hyperdirichlet' package.
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r
